In [1]:
import pandas as pd

In [40]:
media = pd.read_csv('/Users/clkruse/Downloads/0046033-250827131500795/multimedia.txt', sep='\t')
obs = pd.read_csv('/Users/clkruse/Downloads/0046033-250827131500795/occurrence.txt', sep='\t', on_bad_lines='warn')
print("media columns:")
for col in media.columns:
    print(col)
print("obs columns:")
for col in obs.columns:
    print(col)

print(len(obs), len(media))

Skipping line 38440: expected 226 fields, saw 263

/var/folders/34/h1c9l0254jx_h5t42w5cmr5w0000gn/T/ipykernel_21464/933110446.py:2: DtypeWarning: Columns (1,2,3,5,7,8,9,10,11,12,13,14,15,16,18,19,20,22,23,24,25,28,29,33,34,35,36,37,38,40,41,42,43,44,46,47,48,49,50,52,53,54,57,58,59,61,63,69,70,71,73,74,75,76,77,78,79,81,82,85,86,87,88,89,90,92,95,96,102,104,105,107,108,109,110,111,131,132,134,135,136,137,138,139,140,141,147,152,155,170,174,175,178,188,190,213,223,224) have mixed types. Specify dtype option on import or set low_memory=False.
  obs = pd.read_csv('/Users/clkruse/Downloads/0046033-250827131500795/occurrence.txt', sep='\t', on_bad_lines='warn')

media columns:
gbifID
type
format
identifier
references
title
description
source
audience
created
creator
contributor
publisher
license
rightsHolder
obs columns:
gbifID
accessRights
bibliographicCitation
language
license
modified
publisher
references
rightsHolder
type
institutionID
collectionID
datasetID
institutionCode
collectionCode
datasetName
ownerInstitutionCode
basisOfRecord
informationWithheld
dataGeneralizations
dynamicProperties
occurrenceID
catalogNumber
recordNumber
recordedBy
recordedByID
individualCount
organismQuantity
organismQuantityType
sex
lifeStage
reproductiveCondition
caste
behavior
vitality
establishmentMeans
degreeOfEstablishment
pathway
georeferenceVerificationStatus
occurrenceStatus
preparations
disposition
associatedOccurrences
associatedReferences
associatedSequences
associatedTaxa
otherCatalogNumbers
occurrenceRemarks
organismID
organismName
organismScope
associatedOrganisms
previousIdentifications
organismRemarks
materialEntityID
materialEntityRemarks
verbatimLabel
materialSampleID
eventID
parentEventID
eventType
fieldNumber
eventDate
eventTime
startDayOfYear
endDayOfYear
year
month
day
verbatimEventDate
habitat
samplingProtocol
sampleSizeValue
sampleSizeUnit
samplingEffort
fieldNotes
eventRemarks
locationID
higherGeographyID
higherGeography
continent
waterBody
islandGroup
island
countryCode
stateProvince
county
municipality
locality
verbatimLocality
verbatimElevation
verticalDatum
verbatimDepth
minimumDistanceAboveSurfaceInMeters
maximumDistanceAboveSurfaceInMeters
locationAccordingTo
locationRemarks
decimalLatitude
decimalLongitude
coordinateUncertaintyInMeters
coordinatePrecision
pointRadiusSpatialFit
verbatimCoordinateSystem
verbatimSRS
footprintWKT
footprintSRS
footprintSpatialFit
georeferencedBy
georeferencedDate
georeferenceProtocol
georeferenceSources
georeferenceRemarks
geologicalContextID
earliestEonOrLowestEonothem
latestEonOrHighestEonothem
earliestEraOrLowestErathem
latestEraOrHighestErathem
earliestPeriodOrLowestSystem
latestPeriodOrHighestSystem
earliestEpochOrLowestSeries
latestEpochOrHighestSeries
earliestAgeOrLowestStage
latestAgeOrHighestStage
lowestBiostratigraphicZone
highestBiostratigraphicZone
lithostratigraphicTerms
group
formation
member
bed
identificationID
verbatimIdentification
identificationQualifier
typeStatus
identifiedBy
identifiedByID
dateIdentified
identificationReferences
identificationVerificationStatus
identificationRemarks
taxonID
scientificNameID
acceptedNameUsageID
parentNameUsageID
originalNameUsageID
nameAccordingToID
namePublishedInID
taxonConceptID
scientificName
acceptedNameUsage
parentNameUsage
originalNameUsage
nameAccordingTo
namePublishedIn
namePublishedInYear
higherClassification
kingdom
phylum
class
order
superfamily
family
subfamily
tribe
subtribe
genus
genericName
subgenus
infragenericEpithet
specificEpithet
infraspecificEpithet
cultivarEpithet
taxonRank
verbatimTaxonRank
vernacularName
nomenclaturalCode
taxonomicStatus
nomenclaturalStatus
taxonRemarks
datasetKey
publishingCountry
lastInterpreted
elevation
elevationAccuracy
depth
depthAccuracy
distanceFromCentroidInMeters
issue
taxonomicIssue
nonTaxonomicIssue
mediaType
hasCoordinate
hasGeospatialIssues
taxonKey
acceptedTaxonKey
kingdomKey
phylumKey
classKey
orderKey
familyKey
genusKey
subgenusKey
speciesKey
species
acceptedScientificName
verbatimScientificName
typifiedName
protocol
lastParsed
lastCrawled
isInvasive
repatriated
relativeOrganismQuantity
projectId
isSequenced
gbifRegion
publishedByGbifRegion
level0Gid
level0Name
level1Gid
level1Name
level2Gid
level2Name
level3Gid
level3Name
iucnRedListCategory
95812 47367

In [21]:
media.head()

,gbifID,type,format,identifier,references,title,description,source,audience,created,creator,contributor,publisher,license,rightsHolder
0,2249183750,StillImage,image/jpeg,http://www.boldsystems.org/pics/FSHN/FSH.BLDE....,http://bins.boldsystems.org/index.php/Public_R...,FSHN140-19 Lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://creativecommons.org/licenses/by/4.0/,NaN
1,2249183993,StillImage,image/jpeg,http://www.boldsystems.org/pics/FSHN/FSH.HOPB....,http://bins.boldsystems.org/index.php/Public_R...,FSHN222-19 Lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://creativecommons.org/licenses/by/4.0/,NaN
2,2249182179,StillImage,image/jpeg,http://www.boldsystems.org/pics/FSHN/FSH.BLDE....,http://bins.boldsystems.org/index.php/Public_R...,FSHN142-19 Lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://creativecommons.org/licenses/by/4.0/,NaN
3,2249184664,StillImage,image/jpeg,http://www.boldsystems.org/pics/FSHN/FSH.HOPB....,http://bins.boldsystems.org/index.php/Public_R...,FSHN215-19 Lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://creativecommons.org/licenses/by/4.0/,NaN
4,2249181465,StillImage,image/jpeg,http://www.boldsystems.org/pics/FSHN/FSH.BIGC....,http://bins.boldsystems.org/index.php/Public_R...,FSHN131-19 Lateral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://creativecommons.org/licenses/by/4.0/,NaN

In [30]:
single_row = obs.iloc[10000]
for col in single_row.index:
    print(f"{col}: {single_row[col]}")

gbifID: 5192557519
accessRights: https://members.oceantrack.org/data/policies/otn-data-policy
bibliographicCitation: nan
language: nan
license: CC_BY_4_0
modified: nan
publisher: Ocean Tracking Network
references: nan
rightsHolder: Ocean Tracking Network, Dalhousie University, Halifax, Nova Scotia otndc@dal.ca
type: nan
institutionID: KRS
collectionID: nan
datasetID: otnkrskintama2004-2011tag
institutionCode: Kintama Research Services
collectionCode: KNTM
datasetName: Kintama 2004-2011 tags
ownerInstitutionCode: nan
basisOfRecord: MACHINE_OBSERVATION
informationWithheld: nan
dataGeneralizations: nan
dynamicProperties: nan
occurrenceID: otn:NEP.COLR:COLR-RKm676_02-VR3-UWM-53-920_KNTM-805_2010-05-21T0
catalogNumber: otn:NEP.COLR:COLR-RKm676_02-VR3-UWM-53-920_KNTM-805_2010-05-21T0
recordNumber: nan
recordedBy: NEP.COLR
recordedByID: nan
individualCount: 1.0
organismQuantity: nan
organismQuantityType: nan
sex: nan
lifeStage: nan
reproductiveCondition: nan
caste: nan
behavior: nan
vitality: nan
establishmentMeans: nan
degreeOfEstablishment: nan
pathway: nan
georeferenceVerificationStatus: nan
occurrenceStatus: PRESENT
preparations: nan
disposition: nan
associatedOccurrences: nan
associatedReferences: nan
associatedSequences: nan
associatedTaxa: nan
otherCatalogNumbers: nan
occurrenceRemarks: trn_deploy_id: 3082 (qa 1)(rcvr_log 140) Receiver notes(Uploaded on deck)
organismID: KNTM-805
organismName: KNTM-805
organismScope: individual
associatedOrganisms: nan
previousIdentifications: nan
organismRemarks: nan
materialEntityID: nan
materialEntityRemarks: nan
verbatimLabel: nan
materialSampleID: nan
eventID: otn:NEP.COLR:COLR-RKm676_02-VR3-UWM-53-920_KNTM-805_2010-05-21T0
parentEventID: otn:NEP.COLR:COLR-RKm676_02-VR3-UWM-53-920
eventType: nan
fieldNumber: nan
eventDate: 2010-05-21T00:01:50
eventTime: nan
startDayOfYear: 141.0
endDayOfYear: 141.0
year: 2010
month: 5.0
day: 21.0
verbatimEventDate: nan
habitat: nan
samplingProtocol: acoustic detection
sampleSizeValue: nan
sampleSizeUnit: nan
samplingEffort: nan
fieldNotes: nan
eventRemarks: nan
locationID: nan
higherGeographyID: nan
higherGeography: nan
continent: NORTH_AMERICA
waterBody: nan
islandGroup: nan
island: nan
countryCode: US
stateProvince: nan
county: nan
municipality: nan
locality: LINE: Columbia River, STATION: COLR-RKm676_02
verbatimLocality: nan
verbatimElevation: nan
verticalDatum: nan
verbatimDepth: nan
minimumDistanceAboveSurfaceInMeters: nan
maximumDistanceAboveSurfaceInMeters: nan
locationAccordingTo: nan
locationRemarks: nan
decimalLatitude: 46.68377
decimalLongitude: -117.62903
coordinateUncertaintyInMeters: 1000.0
coordinatePrecision: nan
pointRadiusSpatialFit: nan
verbatimCoordinateSystem: nan
verbatimSRS: nan
footprintWKT: POINT(-117.62903 46.68377)
footprintSRS: nan
footprintSpatialFit: nan
georeferencedBy: nan
georeferencedDate: nan
georeferenceProtocol: nan
georeferenceSources: nan
georeferenceRemarks: nan
geologicalContextID: nan
earliestEonOrLowestEonothem: nan
latestEonOrHighestEonothem: nan
earliestEraOrLowestErathem: nan
latestEraOrHighestErathem: nan
earliestPeriodOrLowestSystem: nan
latestPeriodOrHighestSystem: nan
earliestEpochOrLowestSeries: nan
latestEpochOrHighestSeries: nan
earliestAgeOrLowestStage: nan
latestAgeOrHighestStage: nan
lowestBiostratigraphicZone: nan
highestBiostratigraphicZone: nan
lithostratigraphicTerms: nan
group: nan
formation: nan
member: nan
bed: nan
identificationID: nan
verbatimIdentification: nan
identificationQualifier: nan
typeStatus: nan
identifiedBy: nan
identifiedByID: nan
dateIdentified: nan
identificationReferences: nan
identificationVerificationStatus: nan
identificationRemarks: nan
taxonID: nan
scientificNameID: urn:lsid:marinespecies.org:taxname:158075
acceptedNameUsageID: 5204024
parentNameUsageID: nan
originalNameUsageID: nan
nameAccordingToID: nan
namePublishedInID: nan
taxonConceptID: nan
scientificName: Oncorhynchus tshawytscha (Walbaum, 1792)
acceptedNameUsage: nan
parentNameUsage: nan
originalNameUsage: nan
nameAccordingTo: nan
namePublishedIn: nan
namePublishedInYear: nan
higherClassification: nan
kingdom: Animalia
phylum: Chordata
class: nan
order: Salmoniformes
superfamily: nan
family: Salmonidae
subfamily: nan
tribe: nan
subtribe: nan
genus: Oncorhynchus
genericName: Oncorhynchus
subgenus: nan
infragenericEpithet: nan
specificEpithet: tshawytscha
infraspecificEpithet: nan
cultivarEpithet: nan
taxonRank: SPECIES
verbatimTaxonRank: nan
vernacularName: Chinook salmon
nomenclaturalCode: nan
taxonomicStatus: ACCEPTED
nomenclaturalStatus: nan
taxonRemarks: nan
datasetKey: a22dcaec-0a63-46a2-8e12-59453f42599d
publishingCountry: CA
lastInterpreted: 2025-07-05T08:16:29.231Z
elevation: nan
elevationAccuracy: nan
depth: nan
depthAccuracy: nan
distanceFromCentroidInMeters: nan
issue: RECORDED_DATE_INVALID;COUNTRY_DERIVED_FROM_COORDINATES;CONTINENT_DERIVED_FROM_COORDINATES
taxonomicIssue: nan
nonTaxonomicIssue: nan
mediaType: nan
hasCoordinate: True
hasGeospatialIssues: False
taxonKey: 5204024
acceptedTaxonKey: 5204024
kingdomKey: 1
phylumKey: 44
classKey: nan
orderKey: 1313
familyKey: 8615
genusKey: 2351426.0
subgenusKey: nan
speciesKey: 5204024.0
species: Oncorhynchus tshawytscha
acceptedScientificName: Oncorhynchus tshawytscha (Walbaum, 1792)
verbatimScientificName: Oncorhynchus tshawytscha
typifiedName: nan
protocol: EML
lastParsed: 2025-07-05T08:16:29.231Z
lastCrawled: 2025-06-28T00:36:41.350Z
isInvasive: nan
repatriated: True
relativeOrganismQuantity: nan
projectId: nan
isSequenced: False
gbifRegion: NORTH_AMERICA
publishedByGbifRegion: NORTH_AMERICA
level0Gid: USA
level0Name: United States
level1Gid: USA.48_1
level1Name: Washington
level2Gid: USA.48.38_1
level2Name: Whitman
level3Gid: nan
level3Name: nan
iucnRedListCategory: LC

In [45]:
simple_out = pd.DataFrame({
    'gbifID': obs['gbifID'],
    'name': obs['vernacularName'],
    'species': obs['species'],
    'date': obs['eventDate'],
    'country': obs['level0Gid'],
    'state': obs['level1Gid'],
    'lat': obs['decimalLatitude'],
    'lon': obs['decimalLongitude'],
    'publisher': obs['publisher']
})

# join the media table to the simple_out table
# The 'gbifID' column in simple_out is the same as the 'gbifID' column in the media table
# I only want to include the 'identifier' column from the media table

simple_media = pd.DataFrame({
    'gbifID': media['gbifID'],
    'format': media['format'],
    'url': media['identifier']
})

# capitalize the first letter of each word in the 'name' column
simple_out['name'] = simple_out['name'].str.title()

merged = pd.merge(simple_out, simple_media, on='gbifID', how='left')

species_to_remove = [
    'Oncorhynchus tshawytscha',
    'Oncorhynchus kisutch',
    'Oncorhynchus nerka',
    'Oncorhynchus gorbuscha',
    'Oncorhynchus keta',
    'Salmo salar'
    ]

# remove species_to_remove
simple_out = simple_out[~simple_out['species'].isin(species_to_remove)]

print(len(simple_out), len(merged))
simple_out['name'].value_counts()

48894 112554

name
Rainbow Trout                                                                       8908
Brown Trout                                                                         7209
Steelhead Trout                                                                      754
Westslope Cutthroat Trout                                                            312
Splake                                                                               198
Brook Trout                                                                          181
Kamloops Trout                                                                        88
Cutthroat Trout                                                                       76
Snake River Finespotted Cutthroat Trout                                               46
Arctic Grayling                                                                       45
Golden Trout                                                                          37
Salmonids; Salmons; Ray-Finned Fishes; Vertebrates; Chordates; Animals                19
Lake Trout                                                                            12
Cisco                                                                                 12
Sheefish, Es, Ca, Fr, It, De, Dk, No                                                   9
Lake Whitefish                                                                         9
Lake Whitefish, Es, Ca, Fr, It, De, Dk, No                                             8
Bering Cisco, Es, Ca, Fr, It, De, Dk, No                                               8
Lahontan Cutthroat Trout                                                               6
Cutbow Trout                                                                           6
Bull Trout                                                                             5
Sheefish; Salmonids; Salmons; Ray-Finned Fishes; Vertebrates; Chordates; Animals       4
Chars                                                                                  3
Redband Trout                                                                          2
Ohrid Trout                                                                            1
Trout                                                                                  1
Tiger Trout                                                                            1
Salmonids                                                                              1
Dolly Varden                                                                           1
Pacific Salmon                                                                         1
Trouts                                                                                 1
Name: count, dtype: int64

In [ ]:
simple_out['species'].value_counts()

species
Oncorhynchus mykiss        20642
Salmo trutta               11519
Salvelinus fontinalis       5539
Salvelinus namaycush        1501
Oncorhynchus clarkii        1339
Oncorhynchus virginalis     1285
Coregonus hoyi               995
Coregonus artedi             544
Coregonus clupeaformis       503
Thymallus arcticus           409
Coregonus kiyi               349
Prosopium williamsoni        254
Oncorhynchus aguabonita      236
Salvelinus malma             220
Prosopium coulterii          194
Oncorhynchus gilae           193
Salvelinus confluentus       153
Oncorhynchus henshawi        141
Prosopium cylindraceum       125
Coregonus zenithicus         114
Oncorhynchus apache           61
Coregonus sardinella          55
Coregonus nasus               47
Coregonus pidschian           41
Salvelinus alpinus            39
Stenodus leucichthys          30
Coregonus laurettae           27
Coregonus nigripinnis         12
Stenodus nelma                11
Coregonus autumnalis           8
Coregonus nipigon              5
Prosopium gemmifer             2
Coregonus albula               1
Prosopium spilonotus           1
Salmo letnica                  1
Name: count, dtype: int64

In [49]:
len(simple_out)

48894

In [47]:
simple_out[simple_out['name'] == 'Lake Trout']

,gbifID,name,species,date,country,state,lat,lon,publisher
37692,1897255051,Lake Trout,Salvelinus namaycush,2010-05-01,USA,USA.27_1,47.916540,-114.099620,United States Geological Survey
80425,1897256966,Lake Trout,Salvelinus namaycush,2011-09-06,USA,USA.27_1,48.050910,-106.446100,United States Geological Survey
80901,1896995933,Lake Trout,Salvelinus namaycush,2011-11-08,USA,USA.13_1,42.068130,-111.317410,United States Geological Survey
81923,1897245679,Lake Trout,Salvelinus namaycush,2011-10-06,USA,USA.27_1,47.310190,-115.069720,United States Geological Survey
82898,1897151059,Lake Trout,Salvelinus namaycush,2018-01-31,USA,USA.51_1,44.491341,-109.222000,United States Geological Survey
91934,1897263642,Lake Trout,Salvelinus namaycush,2013-12-31,USA,USA.13_1,48.588447,-116.864957,United States Geological Survey
93467,5106603335,Lake Trout,Salvelinus namaycush,2014-12-31,USA,USA.51_1,44.478871,-110.363150,United States Geological Survey
93979,1897256736,Lake Trout,Salvelinus namaycush,2011-01-21,USA,USA.27_1,48.032642,-114.164420,United States Geological Survey
94352,1896995945,Lake Trout,Salvelinus namaycush,2010-11-02,USA,USA.13_1,42.068130,-111.317410,United States Geological Survey
94950,2273114501,Lake Trout,Salvelinus namaycush,2019-05-04,USA,USA.45_1,40.974030,-109.576150,United States Geological Survey
94951,5106602335,Lake Trout,Salvelinus namaycush,2015-12-31,USA,USA.51_1,44.478871,-110.363150,United States Geological Survey
95460,1897255103,Lake Trout,Salvelinus namaycush,2010-05-01,USA,USA.27_1,47.916540,-114.099620,United States Geological Survey

In [50]:
merged.to_csv('/Users/clkruse/Downloads/simple_out_2.csv', index=False)